/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BFSContractionOrder__ */

#ifndef _Included_BFSContractionOrder__
#define _Included_BFSContractionOrder__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BFSContractionOrder__
 * Method:    ord
 * Signature: ([I[[I)J
 */
JNIEXPORT jlong JNICALL Java_BFSContractionOrder_00024_ord
  (JNIEnv *, jobject, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
