/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BFSContractionOrder__ */

#ifndef _Included_BFSContractionOrder__
#define _Included_BFSContractionOrder__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BFSContractionOrder__
 * Method:    x
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_BFSContractionOrder_00024_x
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
