/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class contraction_order_BFSAlg__ */

#ifndef _Included_contraction_order_BFSAlg__
#define _Included_contraction_order_BFSAlg__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     contraction_order_BFSAlg__
 * Method:    ord
 * Signature: ([I[[I)Lcontraction_order/NativeContractionOrderResult;
 */
JNIEXPORT jobject JNICALL Java_contraction_1order_BFSAlg_00024_ord
  (JNIEnv *, jobject, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
