/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_edu_agh_tensia_contraction_order_BFSOrderFinder__ */

#ifndef _Included_pl_edu_agh_tensia_contraction_order_BFSOrderFinder__
#define _Included_pl_edu_agh_tensia_contraction_order_BFSOrderFinder__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_edu_agh_tensia_contraction_order_BFSOrderFinder__
 * Method:    ord
 * Signature: ([I[[I[Z)Lpl/edu/agh/tensia/contraction/order/NativeOrderFinderResult;
 */
JNIEXPORT jobject JNICALL Java_pl_edu_agh_tensia_contraction_order_BFSOrderFinder_00024_ord
  (JNIEnv *, jobject, jintArray, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
